#!/bin/sh
set -e
cd libc && DESTDIR="../sysroot" bear -- make install && cd ..
cd kernel && DESTDIR="../sysroot" bear -- make install && cd ..

mkdir -p iso/boot/grub
cp sysroot/boot/sona.kernel iso/boot/sona.kernel
cat > iso/boot/grub/grub.cfg << EOF
menuentry "sona" {
	multiboot /boot/sona.kernel
}
EOF
grub-mkrescue -o sona.iso iso

